// Built-in word decks categorized for Kids Under 10 and Millennial Adults
export const DECKS = {
  kids: [
    {
      id: "kids-animals",
      name: "Zoo & Animals",
      icon: "🦁",
      color: "#f59e0b",
      description: "Act out or sound like these fun animals!",
      words: [
        { word: "Lion", hint: "Roar! King of the jungle" },
        { word: "Penguin", hint: "Waddle waddle on ice" },
        { word: "Monkey", hint: "Ooh ooh aah aah, loves bananas" },
        { word: "Frog", hint: "Ribbit! Jumping green friend" },
        { word: "Kangaroo", hint: "Boing! Pouch for baby" },
        { word: "Elephant", hint: "Long trunk and big ears" },
        { word: "Snake", hint: "Slithering sss-snake" },
        { word: "Chicken", hint: "Bawk bawk! Lays eggs" },
        { word: "Dog", hint: "Chasing its tail, woof!" },
        { word: "Cat", hint: "Meow! Licking paws" },
        { word: "Dolphin", hint: "Jumping out of the ocean" },
        { word: "T-Rex Dinosaur", hint: "Tiny arms and big stomps" },
        { word: "Butterfly", hint: "Flapping colorful wings" },
        { word: "Giraffe", hint: "Super tall neck eating leaves" },
        { word: "Bunny Rabbit", hint: "Twitching nose and hopping" },
        { word: "Sleeping Bear", hint: "Hibernating and snoring" },
        { word: "Duck", hint: "Quack quack! Swimming in pond" },
        { word: "Cow", hint: "Moo! Chewing grass" },
        { word: "Horse", hint: "Galloping clip-clop" },
        { word: "Shark", hint: "Fin in the water, chomp chomp" },
        { word: "Owl", hint: "Hoo hoo at nighttime" },
        { word: "Gorilla", hint: "Beating its chest" },
        { word: "Crab", hint: "Walking sideways with pinchers" },
        { word: "Cheetah", hint: "Fastest runner on land" },
        { word: "Flamingo", hint: "Standing on one leg" }
      ]
    },
    {
      id: "kids-cartoons",
      name: "Disney & Cartoons",
      icon: "🎬",
      color: "#3b82f6",
      description: "Favorite animated characters and heroes!",
      words: [
        { word: "Elsa", hint: "Frozen: Let It Go!" },
        { word: "Mickey Mouse", hint: "Big round ears & red shorts" },
        { word: "SpongeBob", hint: "Lives in a pineapple under the sea" },
        { word: "Pikachu", hint: "Pika Pika! Electric yellow mouse" },
        { word: "Buzz Lightyear", hint: "To infinity and beyond!" },
        { word: "Spider-Man", hint: "Shooting webs from wrists" },
        { word: "Olaf", hint: "Snowman who loves warm hugs" },
        { word: "Peppa Pig", hint: "Jumping in muddy puddles" },
        { word: "Simba", hint: "Lion cub from Pride Rock" },
        { word: "Minion", hint: "Yellow with goggles: Banana!" },
        { word: "Sonic the Hedgehog", hint: "Super fast blue speedster" },
        { word: "Shrek", hint: "Big green ogre in a swamp" },
        { word: "Nemo", hint: "Little clownfish with lucky fin" },
        { word: "Winnie the Pooh", hint: "Loves eating golden honey" },
        { word: "Batman", hint: "Dark Knight with bat cape" },
        { word: "Woody", hint: "Cowboy with pull-string" },
        { word: "Mario", hint: "Mustache plumber jumping on mushrooms" },
        { word: "Moana", hint: "Sailing across the ocean" },
        { word: "The Hulk", hint: "Hulk smash! Turning green" },
        { word: "Iron Man", hint: "Flying in high-tech metal suit" }
      ]
    },
    {
      id: "kids-actions",
      name: "Silly Actions",
      icon: "🤸",
      color: "#10b981",
      description: "Fun physical actions to act out!",
      words: [
        { word: "Brushing Teeth", hint: "Squeeze paste and scrub scrub" },
        { word: "Eating Spicy Noodles", hint: "Fanning mouth, too hot!" },
        { word: "Riding a Rollercoaster", hint: "Hands in the air screaming" },
        { word: "Walking a Dog", hint: "Holding the leash as it pulls" },
        { word: "Swimming in Cold Water", hint: "Shivering brrr splashing" },
        { word: "Baking a Cake", hint: "Stirring batter and tasting" },
        { word: "Tying Shoelaces", hint: "Make bunny ears and tie" },
        { word: "Loud Snoring", hint: "Sleeping with mouth open" },
        { word: "Kicking a Soccer Ball", hint: "Goal! Running and cheering" },
        { word: "Blowing Birthday Candles", hint: "Make a wish and puff!" },
        { word: "Robot Dance", hint: "Stiff robotic movements" },
        { word: "Climbing a Tree", hint: "Reaching up branch by branch" },
        { word: "Flying an Airplane", hint: "Arms out soaring in clouds" },
        { word: "Melting Ice Cream", hint: "Licking drips quickly" },
        { word: "Catching a Fish", hint: "Reeling in the heavy line" },
        { word: "Playing Drums", hint: "Bang bang on the cymbals" },
        { word: "Jumping on a Trampoline", hint: "Higher and higher bounce" },
        { word: "Looking Through Binoculars", hint: "Hands over eyes searching" },
        { word: "Washing a Car", hint: "Soap suds and hose spray" },
        { word: "Ice Skating", hint: "Gliding and wobbling on ice" }
      ]
    },
    {
      id: "kids-food",
      name: "Yummy Treats & Food",
      icon: "🍕",
      color: "#ec4899",
      description: "Delicious foods everyone loves!",
      words: [
        { word: "Cheesy Pizza", hint: "Pulling gooey cheese slice" },
        { word: "Popcorn", hint: "Popping in microwave, eating at movies" },
        { word: "Messy Spaghetti", hint: "Slurping long sauce noodles" },
        { word: "Ice Cream Cone", hint: "Double scoop with sprinkles" },
        { word: "Watermelon", hint: "Spitting out black seeds" },
        { word: "Cotton Candy", hint: "Fluffy pink sugary cloud" },
        { word: "Peeled Banana", hint: "Peeling down the yellow skin" },
        { word: "Hot Dog", hint: "Ketchup and mustard in a bun" },
        { word: "Crispy French Fries", hint: "Dipping in red ketchup" },
        { word: "Birthday Cake", hint: "Slicing sweet frosted cake" },
        { word: "Glazed Donut", hint: "Round pastry with a hole" },
        { word: "Crunchy Taco", hint: "Tilting head sideways to bite" },
        { word: "Chocolate Bar", hint: "Breaking off a tasty square" },
        { word: "Pancakes with Syrup", hint: "Stack dripping with maple syrup" },
        { word: "Lollipop", hint: "Swirly sweet on a stick" },
        { word: "Crispy Bacon", hint: "Sizzling in the frying pan" },
        { word: "Juicy Burger", hint: "Two hands holding big bite" },
        { word: "Cupcake", hint: "Licking frosting off top" },
        { word: "Strawberries", hint: "Dipping in sweet cream" },
        { word: "Boba Bubble Tea", hint: "Chewing tapioca pearls with fat straw" }
      ]
    },
    {
      id: "kids-vn-animals",
      name: "🐾 Thế Giới Động Vật",
      icon: "🐶",
      color: "#10b981",
      description: "Bắt chước tiếng kêu và điệu bộ các con vật quen thuộc!",
      words: [
        { word: "Con Chó", hint: "Gâu gâu, vẫy đuôi mừng rỡ" },
        { word: "Con Mèo", hint: "Meo meo, liếm lông rửa mặt" },
        { word: "Con Khỉ", hint: "Khẹc khẹc, gãi đầu thích ăn chuối" },
        { word: "Con Ếch", hint: "Ộp ộp, nhảy lò cò thè lưỡi bắt muỗi" },
        { word: "Con Voi", hint: "Vòi dài hút nước, tai to phe phẩy" },
        { word: "Con Gà Trống", hint: "Ò ó o gáy vang sáng sớm" },
        { word: "Con Cá Mập", hint: "Hàm răng nhọn bơi lượn săn mồi" },
        { word: "Con Chuột Túi", hint: "Nhảy tưng tưng, có túi nuôi con nhỏ" },
        { word: "Con Hổ (Cọp)", hint: "Gầm gừ chúa sơn lâm vồ mồi" },
        { word: "Con Bướm", hint: "Đập cánh bay rập rờn hút mật hoa" },
        { word: "Con Cua", hint: "Bò ngang hai càng kẹp kẹp" },
        { word: "Con Ngựa", hint: "Phi nước đại gõ móng cộc cộc" },
        { word: "Con Vịt", hint: "Cạp cạp, bơi lội lạch bạch dưới ao" },
        { word: "Con Chim Cánh Cụt", hint: "Đi lạch bạch trên băng tuyết" },
        { word: "Con Rùa", hint: "Bò chậm chạp rụt đầu vào mai cứng" },
        { word: "Con Thỏ", hint: "Hai tai dài nhảy nhót gặm cà rốt" },
        { word: "Con Heo (Lợn)", hint: "Ụt ịt béo tròn nằm ngủ" },
        { word: "Con Sâu Đo", hint: "Uốn éo bò trên cành cây" },
        { word: "Khủng Long Bạo Chúa", hint: "Dậm chân ầm ầm, hai tay ngắn củn" }
      ]
    },
    {
      id: "kids-vn-cartoons",
      name: "⚡ Hoạt Hình & Siêu Nhân",
      icon: "🦸",
      color: "#3b82f6",
      description: "Các nhân vật truyện tranh và siêu nhân bé yêu thích!",
      words: [
        { word: "Doraemon", hint: "Mèo máy màu xanh mê bánh rán" },
        { word: "Nobita", hint: "Đeo kính tròn hậu đậu hay khóc nhè" },
        { word: "Thám Tử Conan", hint: "Bắn kim gây mê phá án thần sầu" },
        { word: "Pikachu", hint: "Chuột điện màu vàng Pika Pika" },
        { word: "Người Nhện (Spider-Man)", hint: "Bắn tơ đu dây leo trèo trên tường" },
        { word: "Elsa (Nữ Hoàng Băng Giá)", hint: "Hát Let It Go làm phép đóng băng" },
        { word: "Tôn Ngộ Không", hint: "Múa gậy Như Ý, bay trên mây" },
        { word: "Heo Peppa", hint: "Heo hồng thích nhảy trong vũng bùn" },
        { word: "Mèo Tom & Chuột Jerry", hint: "Đuổi bắt nhau chí chóe khắp nhà" },
        { word: "Minion", hint: "Màu vàng đeo kính chuối Banana!" },
        { word: "Siêu Nhân Gao", hint: "Biến hình gầm gừ Gao Ố!" },
        { word: "Songoku (7 Viên Ngọc Rồng)", hint: "Tụ chưởng Kamehameha bắn ra" },
        { word: "Người Sắt (Iron Man)", hint: "Bắn tia năng lượng từ bàn tay" },
        { word: "Chú Bé Bọt Biển (SpongeBob)", hint: "Cười hề hề sống dưới đáy biển" },
        { word: "Chuột Mickey", hint: "Hai tai tròn vẫy tay chào vui vẻ" },
        { word: "Hulk (Người Khổng Lồ Xanh)", hint: "Gồng cơ bắp gầm to đập phá" },
        { word: "Thần Sấm Thor", hint: "Vung búa sét gọi sấm chớp ầm ầm" }
      ]
    },
    {
      id: "kids-vn-actions",
      name: "🤪 Hành Động Tinh Nghịch",
      icon: "🤸",
      color: "#f59e0b",
      description: "Diễn tả hành động hài hước chỉ bằng cử chỉ!",
      words: [
        { word: "Đánh Răng Súc Miệng", hint: "Lấy kem chà răng rồi súc miệng nhổ ra" },
        { word: "Ăn Mì Cay Hít Hà", hint: "Vừa ăn vừa thè lưỡi quạt gió vì cay" },
        { word: "Bị Kiến Cắn Gãi Ngứa", hint: "Gãi ngứa nhảy tưng tưng khắp người" },
        { word: "Thổi Nến Sinh Nhật", hint: "Chắp tay ước rồi phù một hơi thật mạnh" },
        { word: "Đi Xe Đạp Loạng Choạng", hint: "Đang đạp xe bỗng mất thăng bằng ngã nhào" },
        { word: "Giả Vờ Ngủ Ngáy To", hint: "Nhắm mắt há miệng khò khò to tiếng" },
        { word: "Uống Trà Sữa Nghẹn Trân Châu", hint: "Hút mạnh bị hạt trân châu bắn vào cổ" },
        { word: "Tập Thể Dục Buổi Sáng", hint: "Vươn vai hít thở một hai ba bốn" },
        { word: "Bắn Súng Nước", hint: "Bóp cò xịt nước té ướt sũng bạn bè" },
        { word: "Lau Nhà Trượt Chân", hint: "Cầm cây lau nhà xoay vòng rồi trượt té" },
        { word: "Hát Karaoke Say Sưa", hint: "Cầm micro gào to nhập tâm hết mình" },
        { word: "Đập Muỗi Hụt", hint: "Đập hai tay bốp nhưng muỗi bay mất" },
        { word: "Ăn Kem Chảy Nước", hint: "Kem nhỏ giọt liếm lia lịa không kịp" },
        { word: "Nhảy Dây Vấp Chân", hint: "Đang quăng dây nhảy thì vướng chân té" },
        { word: "Rửa Mặt Kiểu Mèo", hint: "Lấy hai tay quẹt quẹt lên má rửa mặt" },
        { word: "Lái Ô Tô Bấm Còi", hint: "Cầm vô lăng bóp còi tin tin tránh đường" }
      ]
    },
    {
      id: "kids-vn-food",
      name: "🍦 Món Ngon Bé Thích",
      icon: "🍧",
      color: "#ec4899",
      description: "Những món ăn khoái khẩu và quà vặt quen thuộc!",
      words: [
        { word: "Kem Ốc Quế", hint: "Cầm cây kem chóp nhọn liếm ngon lành" },
        { word: "Trà Sữa Trân Châu", hint: "Cắm ống hút to nhai trân châu dai dai" },
        { word: "Bánh Mì Kẹp Thịt", hint: "Cắn miếng giòn rụm pate thơm nức" },
        { word: "Bắp Rang Bơ", hint: "Vừa xem phim vừa bốc ăn liên tục" },
        { word: "Khoai Tây Chiên", hint: "Chấm tương cà đỏ au giòn rụm" },
        { word: "Bánh Tráng Nướng", hint: "Pizza Việt Nam nướng than hồng giòn tan" },
        { word: "Xúc Xích Nướng", hint: "Xiên que xúc xích thơm lừng chấm tương" },
        { word: "Kẹo Mút Tròn", hint: "Cầm que kẹo mút ngọt ngào ngậm một bên má" },
        { word: "Bát Phở Bò", hint: "Gắp sợi bánh phở húp nước dùng xì xụp" },
        { word: "Quả Dưa Hấu", hint: "Cắn miếng đỏ ngọt rồi nhằn hạt đen" },
        { word: "Kẹo Bông Gòn", hint: "Cây kẹo mây hồng ngọt tan ngay trong miệng" },
        { word: "Bánh Bao Nóng Hổi", hint: "Bẻ đôi bánh khói bốc nghi ngút có trứng cút" },
        { word: "Cơm Tấm Sườn Bì", hint: "Cầm miếng sườn nướng thơm phức gặm ngon tuyệt" },
        { word: "Chè Khúc Bạch", hint: "Món chè mát lạnh thạch phô mai béo ngậy" },
        { word: "Hũ Xoài Lắc", hint: "Cầm hũ lắc lắc muối ớt cay xè thơm lừng" }
      ]
    },
    {
      id: "kids-vn-jobs",
      name: "🚒 Nghề Nghiệp Ước Mơ",
      icon: "👮‍♂️",
      color: "#8b5cf6",
      description: "Những nghề nghiệp thú vị bé ước mơ lớn lên làm!",
      words: [
        { word: "Chú Cảnh Sát Giao Thông", hint: "Tuýt còi giơ gậy chỉ huy xe cộ qua lại" },
        { word: "Lính Cứu Hỏa", hint: "Vác vòi rồng xịt nước dập tắt đám lửa" },
        { word: "Bác Sĩ Khám Bệnh", hint: "Đeo ống nghe đập thình thịch rồi tiêm thuốc" },
        { word: "Cô Giáo Dạy Học", hint: "Cầm phấn viết bảng gọi học sinh phát biểu" },
        { word: "Đầu Bếp Siêu Đẳng", hint: "Đội mũ cao xào chảo lửa bùng lên nếm sốt" },
        { word: "Phi Hành Gia", hint: "Mặc đồ vũ trụ lơ lửng bước đi trên mặt trăng" },
        { word: "Cầu Thủ Đá Bóng", hint: "Sút bóng vào lưới rồi trượt đầu gối ăn mừng" },
        { word: "Ca Sĩ Biểu Diễn", hint: "Cầm mic nhảy múa hát vang dưới ánh đèn" },
        { word: "Thợ Cắt Tóc", hint: "Cầm kéo xoẹt xoẹt chải đầu tạo kiểu" },
        { word: "Nhà Ảo Thuật", hint: "Rút khăn biến ra chim bồ câu từ chiếc mũ" },
        { word: "Bác Nông Dân", hint: "Đội nón lá cuốc đất gặt lúa trên đồng" },
        { word: "Phi Công Lái Máy Bay", hint: "Đeo tai nghe điều khiển cần lái bay lên mây" },
        { word: "Chú Thợ Xây", hint: "Trộn hồ xúc xi măng đặt từng viên gạch xây nhà" },
        { word: "Họa Sĩ Vẽ Tranh", hint: "Cầm bảng màu quẹt cọ lên khung vẽ nghệ thuật" },
        { word: "Nhiếp Ảnh Gia", hint: "Cầm máy ảnh ngắm nghía bấm tách tách tạo dáng" }
      ]
    }
  ],

  adults: [
    {
      id: "millennial-nostalgia",
      name: "90s & 2000s Nostalgia",
      icon: "📼",
      color: "#8b5cf6",
      description: "Artifacts and rituals of our youth!",
      words: [
        { word: "Dial-up Internet", hint: "Screeching modem connecting sound" },
        { word: "Tamagotchi Dying", hint: "Forgot to feed virtual pet in pocket" },
        { word: "Rewinding a VHS Tape", hint: "Be kind, rewind before returning" },
        { word: "LimeWire Download", hint: "Song title.mp3 took 3 hours (got a virus)" },
        { word: "MySpace Top 8", hint: "Ranking best friends drama" },
        { word: "Blockbuster Late Fee", hint: "Forgot to return DVD on Friday night" },
        { word: "Nokia 3310 Snake", hint: "Indestructible phone, record score" },
        { word: "Walkman Skipping", hint: "Jogging made the CD player skip" },
        { word: "AIM Away Message", hint: "Cryptic emo lyrics: ~*away*~" },
        { word: "Scholastic Book Fair", hint: "Lamborghini posters & spy pens" },
        { word: "Furby Waking Up", hint: "Talking at 3 AM from closet" },
        { word: "T9 Texting", hint: "Pressing 4-4-3-3-5-5-5-5-6-6-6 blindly" },
        { word: "Capri Sun Pouch", hint: "Straw stabbed all the way through the back" },
        { word: "Heelys Shoes", hint: "Rolling through the shopping mall" },
        { word: "Blowing Nintendo Cartridge", hint: "Fixing gray cartridge with a blow" },
        { word: "Burning a Mix CD", hint: "Sharpie labels for high school crush" },
        { word: "Game Boy Under Covers", hint: "Playing with worm light past bedtime" },
        { word: "Slap Bracelets", hint: "Slapping metal bands on wrists" },
        { word: "Gel Pens Collection", hint: "Sparkly glitter pens on black paper" },
        { word: "MSN Messenger Nudge", hint: "Shaking the chat screen to get attention" }
      ]
    },
    {
      id: "millennial-media",
      name: "Iconic TV & Movies",
      icon: "📺",
      color: "#06b6d4",
      description: "Quotable movies and binge-worthy shows!",
      words: [
        { word: "Friends: Pivot!", hint: "Ross, Chandler, and Rachel on stairs" },
        { word: "The Office: Jim Look", hint: "Staring deadpan at the camera" },
        { word: "Mean Girls: Pink", hint: "On Wednesdays we wear pink" },
        { word: "Harry Potter: Golden Snitch", hint: "Catching the winged golden ball" },
        { word: "Shrek's Swamp", hint: "What are you doing in my swamp?!" },
        { word: "Legally Blonde Bend & Snap", hint: "Elle Woods teaching salon patrons" },
        { word: "High School Musical", hint: "We're all in this together jump" },
        { word: "The Matrix Bullet Dodge", hint: "Neo bending backwards in slow motion" },
        { word: "Titanic: I'm Flying", hint: "Jack and Rose at the bow of the ship" },
        { word: "Lord of the Rings: My Precious", hint: "Gollum crouching over the One Ring" },
        { word: "Gordon Ramsay: Idiot Sandwich", hint: "Holding bread against someone's face" },
        { word: "Twilight: Sparkling Vampire", hint: "Skin of a killer, Bella!" },
        { word: "Superbad: McLovin", hint: "Fake Hawaiian driver license ID" },
        { word: "Zoolander: Blue Steel", hint: "Male model duckface pout" },
        { word: "Borat: Very Nice!", hint: "High five, great success!" },
        { word: "Napoleon Dynamite Dance", hint: "Vote for Pedro auditorium routine" },
        { word: "Kill Bill Whistle", hint: "Yellow tracksuit katana duel" },
        { word: "Devil Wears Prada", hint: "That's all. Throwing coat on desk" }
      ]
    },
    {
      id: "millennial-adulting",
      name: "Adulting & Struggles",
      icon: "🥑",
      color: "#14b8a6",
      description: "The painful humor of turning 30+!",
      words: [
        { word: "Avocado Toast & Iced Latte", hint: "Why we can't afford a house" },
        { word: "Can We Just Text?", hint: "Refusing to pick up unexpected phone call" },
        { word: "Mysterious Back Pain", hint: "Slept slightly wrong on pillow" },
        { word: "Canceling Friday Plans", hint: "Relief of staying home in sweatpants" },
        { word: "Sunday Scaries", hint: "Dread of Monday morning creeping in" },
        { word: "Overthinking an Emoji", hint: "Did they mean that passively aggressively?" },
        { word: "Ghosting", hint: "Vanishing into thin air mid-conversation" },
        { word: "Plant Parent", hint: "Talking to monsteras and fiddle leaf figs" },
        { word: "87 Open Browser Tabs", hint: "I'll read these eventually, I promise" },
        { word: "Costco Bulk Run", hint: "48 rolls of toilet paper and $1.50 hot dog" },
        { word: "Unsubscribing from Emails", hint: "Daily battle against 100 newsletters" },
        { word: "Air Fryer Obsession", hint: "Reheats anything in 5 minutes" },
        { word: "Closing 40 Apps", hint: "Swiping up furiously to save battery" },
        { word: "Checking Zillow for Fun", hint: "Mansions we will never buy" },
        { word: "Leaving Party Without Saying Bye", hint: "The Irish goodbye masterclass" },
        { word: "Drinking from Giant Stanley Cup", hint: "40oz tumbler clanking everywhere" },
        { word: "Meal Prep Sunday", hint: "Same chicken and broccoli for 5 days" },
        { word: "Target Impulse Buy", hint: "Came for milk, spent $180" }
      ]
    },
    {
      id: "millennial-music",
      name: "90s & 2000s Bangers",
      icon: "🎤",
      color: "#e11d48",
      description: "Radio anthems we all still know by heart!",
      words: [
        { word: "Britney Spears: Hit Me Baby", hint: "Pigtails, schoolgirl uniform dance" },
        { word: "Backstreet Boys", hint: "Tell me why! Ain't nothing but a heartache" },
        { word: "Blink-182", hint: "Running naked in What's My Age Again" },
        { word: "Eminem: Mom's Spaghetti", hint: "Palms are sweaty, knees weak, arms are heavy" },
        { word: "Beyoncé: Single Ladies", hint: "Put a ring on it hand flick" },
        { word: "Linkin Park Screaming", hint: "In the end it doesn't even matter!" },
        { word: "Outkast: Hey Ya!", hint: "Shake it like a Polaroid picture" },
        { word: "Spice Girls: Wannabe", hint: "If you wanna be my lover" },
        { word: "Rickroll", hint: "Never gonna give you up dancing" },
        { word: "Avril Lavigne: Sk8er Boi", hint: "He was a boy, she was a girl" },
        { word: "Smash Mouth: All Star", hint: "Somebody once told me the world is gonna roll me" },
        { word: "Evanescence: Bring Me to Life", hint: "Wake me up inside! Can't wake up!" },
        { word: "Nelly: Hot in Herre", hint: "Band-aid on the cheek" },
        { word: "T-Pain Autotune", hint: "Robot singing about Apple Bottom Jeans" },
        { word: "Green Day: Boulevard", hint: "I walk a lonely road, the only one I have ever known" }
      ]
    }
  ]
};
